# Generated by Django 4.2.8 on 2023-12-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam',
            name='height',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='length',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='weight',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
