# Generated by Django 4.2.8 on 2023-12-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_alter_iteam_height_alter_iteam_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam',
            name='height',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='length',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='weight',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
