# Generated by Django 4.2.8 on 2023-12-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_alter_iteam_height_alter_iteam_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteam',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
